### PR TITLE
Add RegisterMatchingEngineMessage

### PR DESCRIPTION
**Pull request by TannerKvarfordt**
Implemented `RegisterMatchingEngineMessage` and its corresponding test class.

### CODE REVIEW

**Comment by TannerKvarfordt** [comment]
We currently don't have a response message listed in our implementation. I assume that's an oversight and we do want to implement a response message?

**Comment by CarsonBradshaw** [comment]
> We currently don't have a response message listed in our implementation. I assume that's an oversight and we do want to implement a response message?

I'm pretty sure that's what our Ack is for. I think our diagram just had a misnamed message. "RegisterMatchingEngineConfirmation" should have just been Ack I believe.

**Comment by CarsonBradshaw** [comment]
@TannerKvarfordt What do you think? Should we rename to RegisterMatchingEngineConfirmation instead? Or just leave it as a general purpose Ack?

**Comment by TannerKvarfordt** [comment]
I think we can leave it as a general purpose Ack for now. I had just forgotten.

**Pull request merged**
