### PR TITLE
Allow Player and Gateway to communicate

### PR DESCRIPTION
**Pull request by Palexander21**
I added a parameter to the UdpCommunicator constructor so that it can bind the datagram channel. The gateway should bind to localhost and port 2000. The Players should bind to null and just send a message to the server address and port. Also I don't know why all these old commits are on this PR. I made a new branch off of master and only added the most recent commit.

### CODE REVIEW

**Comment by Palexander21** [comment]
Also, how do I avoid all those stupid merge branch... commits?

**Comment by TannerKvarfordt** [comment]
@Palexander21 If the repo can't be fast-forwarded, I'm not sure you can avoid the 'merge branch' commits. You might be able to avoid them by [rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) instead of merging, but I'm not sure. @CarsonBradshaw can probably give better advice.

**Comment by CarsonBradshaw** [comment]
@Palexander21 when you are pulling from master into your branch use `git pull --rebase` and you will avoid the merge commits.

**Comment by Palexander21** [comment]
👍

**Pull request merged**
